import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";

const prompt = Prompt({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Food Tracker App",
  description: "Generated by NinniN SAU",
  keywords: ["Food", "Tracker", "อาหาร", "สุขภาพ", "Health"],
  icons: {
    icon: "/vercel.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${prompt.className} antialiased bg-slate-50 text-slate-800 min-h-screen flex flex-col selection:bg-blue-200 selection:text-blue-900`}>
        {children}
      </body>
    </html>
  );
}
